FPS = 100
DT = 1 / FPS
MAX_TIME = 20
MAX_STEPS = int(MAX_TIME * FPS)

USE_TOROIDAL_COORD = True

WIDTH, HEIGHT  = (1920, 1080)


BOUNDARY_WIDTH, BOUNDARY_HEIGHT = (WIDTH, HEIGHT)

N_PREY = 100
N_PREDATORS = 1


# Boid parameters
PREY_CRUISE_VELOCITY = 200.0  # Effectively mininmum velocity
PREY_MAX_VELOCITY = 200.0
PREY_BASE_ACCELERATION = 2500.0
PREY_MAX_ACCELERATION = 2500.0
PREY_MAX_ROTATION_ANGLE = 90  # NOTE: This parameter depends on the acceleration...
PREY_PERCEPTION_RADIUS = 750
PREY_SEPARATION_DISTANCE = 50
# NOTE: FOV has to be halved, because we have FOV/2 on each of the 2 sides
PREY_FOV = 240 // 2
PREY_ESCAPE_REACTION_TIME = 0.0  # sec
PREY_PREDATOR_REPEL_DISTANCE = PREY_PERCEPTION_RADIUS


PREDATOR_CRUISE_VELOCITY = 500.0 #500.0  # Effectively minimum velocity
PREDATOR_MAX_VELOCITY = 500.0 #800.0 # was 400 for the data before
PREDATOR_BASE_ACCELERATION = 5000.0 #1600.0
PREDATOR_MAX_ACCELERATION = 5000.0 #3500.0
PREDATOR_MAX_ROTATION_ANGLE = 90  # NOTE: This parameter depends on the acceleration...
PREDATOR_PERCEPTION_RADIUS = 3000
PREDATOR_SEPARATION_DISTANCE = 100
# NOTE: Has to be halved, because we have FOV/2 on each of the 2 sides
PREDATOR_FOV = 120 // 2
PREDATOR_CONFUSION_RADIUS = PREDATOR_SEPARATION_DISTANCE





# Behaviour parameters - These were evolved so these values are not used
PREY_SEPARATION_COEFFICIENT = 1
PREY_COHESION_COEFFICIENT = 0.01
PREY_ALIGNMENT_COEFFICIENT = 0.12
PREY_DODGE_COEFFICIENT = 10
PREY_REPEL_COEFFICIENT = 10
PREY_WIGGLE_COEFFICIENT = 0.1